title: X-brewing
email: disjfa@disjfa.nl
description: >
  X-brewing
baseurl: ""
url: "https://disjfa.github.io"

# Google
google_analytics: UA-83598448-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

source: site
host: 0.0.0.0

collections:
  beers:
    output: true

facebook_url: https://www.facebook.com/X-brewing-169771763610772/
untapped_url: https://untappd.com/Xbrewing
